# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20170222_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keeper', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('playmaking', models.IntegerField()),
                ('winger', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('scoring', models.IntegerField()),
                ('set_pieces', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Team')),
            ],
        ),
    ]
