# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField()),
                ('old_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
                ('skill', models.CharField(choices=[('keeper', 'keeper'), ('defending', 'defending'), ('playmaking', 'playmaking'), ('winger', 'winger'), ('passing', 'passing'), ('scoring', 'scoring'), ('set_pieces', 'set_pieces')], max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Player')),
            ],
        ),
    ]
